[package]
name = "arkworks_zkp_test"
version = "0.1.0"
edition = "2024"

[dependencies]
ark-ff = "0.4.0"
ark-relations = "0.4.0"
ark-snark = "0.4.0"
ark-groth16 = "0.4.0"
ark-bls12-381 = "0.4.0"
ark-std = { version = "0.4.0", features = ["std"] }
rand = "0.8"
